# Generated by Django 5.1.4 on 2024-12-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('taste', models.CharField(choices=[('sweet', 'Sweet'), ('spicy', 'Spicy'), ('sour', 'Sour')], max_length=50)),
                ('cuisine_type', models.CharField(blank=True, max_length=100, null=True)),
                ('preparation_time', models.PositiveIntegerField(help_text='Time in minutes')),
                ('reviews', models.FloatField(default=0.0)),
            ],
        ),
    ]
